server.port=8082
spring.application.name=notification-service

# ---- Observability ----
management.endpoints.web.exposure.include=health,prometheus
management.tracing.sampling.probability=1.0
management.otlp.tracing.endpoint=http://tempo:4318/v1/traces
